CREATE TABLE country (
  id_country SERIAL PRIMARY KEY,
  name VARCHAR(32) NOT NULL
);
INSERT INTO country (name)
VALUES ('Afghanistan'),
  ('Albania'),
  ('Algeria'),
  ('Andorra'),
  ('Angola'),
  ('Antigua and Barbuda'),
  ('Argentina'),
  ('Armenia'),
  ('Australia'),
  ('Austria'),
  ('Azerbaijan'),
  ('Bahamas'),
  ('Bahrain'),
  ('Bangladesh'),
  ('Barbados'),
  ('Belarus'),
  ('Belgium'),
  ('Belize'),
  ('Benin'),
  ('Bermuda'),
  ('Bhutan'),
  ('Bolivia'),
  ('Bosnia and Herzegovina'),
  ('Botswana'),
  ('Brazil'),
  ('British Virgin Isles'),
  ('Brunei'),
  ('Bulgaria'),
  ('Burkina Faso'),
  ('Burma'),
  ('Burundi'),
  ('Cambodia'),
  ('Cameroon'),
  ('Canada'),
  ('Cape Verde'),
  ('Central African Republic'),
  ('Chad'),
  ('Chile'),
  ('China'),
  ('Christmas Island'),
  ('Cocos Islands'),
  ('Colombia'),
  ('Comoros'),
  ('Congo'),
  ('Cook Islands'),
  ('Costa Rica'),
  ('Cote dIvoire'),
  ('Croatia'),
  ('Cuba'),
  ('Cyprus'),
  ('Czech Republic'),
  ('Denmark'),
  ('Djibouti'),
  ('Dominica'),
  ('Dominican Republic'),
  ('East Timor'),
  ('Ecuador'),
  ('Egypt'),
  ('El Salvador'),
  ('England'),
  ('Equatorial Guinea'),
  ('Eritrea'),
  ('Estonia'),
  ('Ethiopia'),
  ('Falkland Islands'),
  ('Faroe Islands'),
  ('Fiji'),
  ('Finland'),
  ('France'),
  ('French Guiana'),
  ('French Polynesia'),
  ('French Southern Territory'),
  ('Gabon'),
  ('Gambia'),
  ('Georgia'),
  ('Germany'),
  ('Ghana'),
  ('Gibraltar'),
  ('Greece'),
  ('Greenland'),
  ('Grenada'),
  ('Guadeloupe'),
  ('Guam'),
  ('Guatemala'),
  ('Guinea'),
  ('Guinea Bissau'),
  ('Guyana'),
  ('Haiti'),
  ('Honduras'),
  ('Hong Kong'),
  ('Hungary'),
  ('Iceland'),
  ('India'),
  ('Indonesia'),
  ('Iran'),
  ('Iraq'),
  ('Ireland'),
  ('Israel'),
  ('Italy'),
  ('Ivory Coast'),
  ('Jamaica'),
  ('Japan'),
  ('Jordan'),
  ('Kazakhstan'),
  ('Kenya'),
  ('Kiribati'),
  ('Kuwait'),
  ('Kyrgyzstan'),
  ('Laos'),
  ('Latvia'),
  ('Lebanon'),
  ('Lesotho'),
  ('Liberia'),
  ('Libya'),
  ('Liechtenstein'),
  ('Lithuania'),
  ('Luxembourg'),
  ('Macau'),
  ('Macedonia'),
  ('Madagascar'),
  ('Malawi'),
  ('Malaysia'),
  ('Maldives'),
  ('Mali'),
  ('Malta'),
  ('Marshall Islands'),
  ('Martinique'),
  ('Mauritania'),
  ('Mauritius'),
  ('Mayotte'),
  ('Mexico'),
  ('Micronesia'),
  ('Moldova'),
  ('Monaco'),
  ('Mongolia'),
  ('Montserrat'),
  ('Morocco'),
  ('Mozambique'),
  ('Namibia'),
  ('Nauru'),
  ('Nepal'),
  ('Netherlands'),
  ('Netherlands Antilles'),
  ('New Caledonia'),
  ('New Zealand'),
  ('Nicaragua'),
  ('Niger'),
  ('Nigeria'),
  ('Niue'),
  ('Norfolk Island'),
  ('North Korea'),
  ('Northern Mariana Isles'),
  ('Norway'),
  ('Oman'),
  ('Pakistan'),
  ('Panama'),
  ('Papua New Guinea'),
  ('Paraguay'),
  ('Peru'),
  ('Philippines'),
  ('Pitcairn'),
  ('Poland'),
  ('Portugal'),
  ('Puerto Rico'),
  ('Qatar'),
  ('Reunion'),
  ('Romania'),
  ('Russia'),
  ('Rwanda'),
  ('Saint Helena'),
  ('Saint Kitts and Nevis'),
  ('Saint Lucia'),
  ('Saint Pierre and Miquelon'),
  ('Saint Vincent and the Grenadines'),
  ('Samoa'),
  ('San Marino'),
  ('Sao Tome and Principe'),
  ('Saudi Arabia'),
  ('Scotland'),
  ('Senegal'),
  ('Serbia Montenegro'),
  ('Seychelles'),
  ('Sierra Leone'),
  ('Singapore'),
  ('Slovakia'),
  ('Slovenia'),
  ('Solomon Islands'),
  ('Somalia'),
  ('South Africa'),
  ('South Korea'),
  ('Spain'),
  ('Sri Lanka'),
  ('Sudan'),
  ('Suriname'),
  ('Swaziland'),
  ('Sweden'),
  ('Switzerland'),
  ('Syria'),
  ('Taiwan'),
  ('Tajikistan'),
  ('Tanzania'),
  ('Thailand'),
  ('Togo'),
  ('Tokelau'),
  ('Tonga'),
  ('Trinidad and Tobago'),
  ('Tunisia'),
  ('Turkey'),
  ('Turkmenistan'),
  ('Turks and Caicos Islands'),
  ('Tuvalu'),
  ('Uganda'),
  ('Ukraine'),
  ('United Arab Emirates'),
  ('United Kingdom'),
  ('United States'),
  ('Uruguay'),
  ('Uzbekistan'),
  ('Vanuatu'),
  ('Vatican'),
  ('Venezuela'),
  ('Vietnam'),
  ('Virgin Isles'),
  ('Wales'),
  ('Wallis and Futuna'),
  ('Western Sahara'),
  ('Yemen'),
  ('Yugoslavia'),
  ('Zambia'),
  ('Zimbabwe');
CREATE TABLE player (
  id_player SERIAL PRIMARY KEY,
  name VARCHAR(12) NOT NULL,
  -- A null value here means that the player has no pic.
  pic_file_extension CHAR(3) NULL,
  id_country INTEGER NULL,
  city VARCHAR(30) NULL,
  email VARCHAR(50) NULL,
  homepage VARCHAR(250) NULL,
  last_seen BIGINT NULL,
  CONSTRAINT fk_player_country FOREIGN KEY (id_country) REFERENCES country (id_country) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE levelpack (
  id_levelpack SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  prc_name VARCHAR(50) NOT NULL,
  -- 0 hits means built-in levelpack.
  hits INTEGER NOT NULL,
  creator VARCHAR(200) NULL,
  -- Rating and difficulty represent values multiplied by 4 to save space, that is:
  -- 3 == 0.75
  -- 8 == 2
  -- 11 == 2.75
  rating SMALLINT NULL,
  difficulty SMALLINT NULL,
  uploaded DATE NOT NULL,
  bod_version CHAR(3) NOT NULL
)